### PR TITLE
Mac's initial commit for three figure files.

### PR DESCRIPTION
**Pull request by MacCampbell**
Some of the data files are way to big to be included such as the worldclim data. However, I did include as .rdas the genind objects, about 1 Mb each.

There are some extra things that happen in two of the scripts, but, they only write the desired output!!

### CODE REVIEW

**Comment by eriqande** [comment]
Hey Mac!

SCRATCH THIS NOTE FROM ME, SEE BELOW!

This looks great!  It would be great if you could rename the R files a little bit.  Does E8ab.R mean it is for Figure 8 a and b?   

If you could rename things starting with a number, starting at 201 (your stuff will be the 200 series!), in the order scripts should be run, and then give them more informative names, like:

201-create-Figure-8-a-and-b.R

or 

202-prepare-output-for-processing-by-203.R

etc.  

That would be super!  I'll pull it in after that.

Thanks for getting this in here so quickly.  

eric

**Comment by eriqande** [comment]
Hey Mac!

Super cool.  I can see which figures those go to and can rename as I see fit.

I'll pull these in.

Thanks again.  You da man.  Safe travels!

eric

**Comment by MacCampbell** [comment]
Hi Eric,

Great! Yeah, I wasn't sure where you were going with the naming at the
time. Hope it wasn't much trouble for you to clean up my mess.

Mac

**Comment by eriqande** [comment]
No problem at all Bro-ski!

😎

**Pull request merged**
